In [1]:
import pandas as pd
import sqlite3

In [2]:
# CONNECT TO DATABASE
database = 'ssc_database.db'

connection_db = sqlite3.connect(database)
cursor = connection_db.cursor()

In [3]:
tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", connection_db)
tables

,type,name,tbl_name,rootpage,sql
0,table,locations,locations,2,CREATE TABLE locations (\n loca...
1,table,event_types,event_types,4,CREATE TABLE event_types (\n et...
2,table,partners,partners,7,CREATE TABLE partners (\n partn...
3,table,events,events,9,CREATE TABLE events (\n event_i...
4,table,participants,participants,10,CREATE TABLE participants (\n p...
5,table,event_registration,event_registration,14,CREATE TABLE event_registration (\n ...
6,table,event_registered_attendee,event_registered_attendee,18,CREATE TABLE event_registered_attendee (\n ...

In [5]:
# IMPORT SAMPLE DATABASE
location_df = pd.read_csv('locations.csv')
event_type_df = pd.read_csv('event_type.csv')
events_df = pd.read_csv('events.csv')
participants_df = pd.read_csv('participants.csv')
event_regis_df = pd.read_csv('event_registration.csv')
event_regis_attendee_df = pd.read_csv('registered_attendee.csv')
partner_df = pd.read_csv('partners.csv')

### LOCATIONS TABLE

In [6]:
# LOCATION
location_df.to_sql('locations', connection_db, if_exists='append', index=False)

2

In [7]:
table_locations = pd.read_sql("SELECT * FROM locations;", connection_db)
table_locations

,location_id,location_name,street_number,postal_code,city,country
0,L001,De Wilg,Mecklenburglaan 3-5,3581 NV,Utretch,NL
1,L002,Tolhuistuin,Ijpromenade 2,1031 KT,Amsterdam,NL

In [8]:
# SCHEMA INFO
schema_locations = pd.read_sql("PRAGMA table_info(locations);", connection_db)
schema_locations

   cid           name          type  notnull dflt_value  pk
0    0    location_id   VARCHAR(10)        1       None   1
1    1  location_name  VARCHAR(255)        1       None   0
2    2  street_number  VARCHAR(255)        1       None   0
3    3    postal_code    VARCHAR(8)        0       None   0
4    4           city  VARCHAR(150)        0       None   0
5    5        country  VARCHAR(150)        0       None   0

### EVENT TYPES TABLE

In [ ]:
event_type_df.to_sql('event_types', connection_db, if_exists='append', index=False)
table_event_types = pd.read_sql("SELECT * FROM event_types;", connection_db)
table_event_types

  etype_id       etype_name
0      UGF    Uitgaansfeest
1      VMR  Vraag Maar Raak
2      SPR           Sports
3      OTH           Others

In [10]:
schema_event_types = pd.read_sql("PRAGMA table_info(event_types);", connection_db)
schema_event_types

   cid        name          type  notnull dflt_value  pk
0    0    etype_id    VARCHAR(5)        1       None   1
1    1  etype_name  VARCHAR(255)        1       None   0

### PARTNERS TABLE

partner_df.to_sql('partners', connection_db, if_exist)